#!/bin/bash

echo "Enter 2 numbers"
read n1 n2
m=$n1

if [ $n2 -lt $n1 ]
then
	m=$n2
fi

while [ $m -ne 0 ]
do
	x=`expr $n1 % $m`
	y=`expr $n2 % $m`
	if [ $x -eq 0 -a $y -eq 0 ]
	then
		echo "GCD is $m"
	break
	fi
	m=`expr $m - 1`
done
